# Banking Dataset – EDA + Cleaning + Visualizations (Practice Notebook)

**Goal:** Practice all basic EDA functions (head/shape/info/describe/value_counts/isnull/nunique/sort/filter/query/loc/iloc/groupby/pivot/crosstab/corr/replace/strip/bins/duplicates) + **type conversion** + **matplotlib visualizations**.

✅ No encoders

✅ Focus on Pandas + Matplotlib

---

## 1) Load data

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd #elias
import numpy as np


df = pd.read_csv("banking.csv")#comma sepearated version #missing #N/A #nan #-
df.head()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
0,200001,22,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",498.0,Yes,No,Yes,2,28449,3,Charges,No
1,200002,58,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,727.0,Yes,Yes,Yes,18,33378,4,Card,No
2,200003,52,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",310.0,Yes,Yes,Yes,20,19283,6,Charges,No
3,200004,40,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,399.0,No,Yes,No,60,16949,1,NaN,No
4,200005,40,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,369.0,No,No,Yes,36,25336,1,Digital Banking,No

## 2) Quick structure checks

In [ ]:
df.shape #number of rows, number of columns

(10120, 20)

In [ ]:
df.columns

Index(['CustomerID', 'Age', 'Job', 'Marital', 'Education', 'City', 'Channel',
       'Segment', 'AccountOpenDate', 'MonthlyIncome', 'Balance', 'CreditScore',
       'HasHousingLoan', 'HasPersonalLoan', 'HasCreditCard',
       'TransactionsLastMonth', 'AvgTxnAmount', 'ComplaintsLast6M',
       'ComplaintType', 'Churned'],
      dtype='object')

In [ ]:
df.dtypes #STRING(OBJECT),Integer, Floats, Boolean, None

CustomerID                 int64
Age                        int64
Job                       object
Marital                   object
Education                 object
City                      object
Channel                   object
Segment                   object
AccountOpenDate           object
MonthlyIncome             object
Balance                   object
CreditScore              float64
HasHousingLoan            object
HasPersonalLoan           object
HasCreditCard             object
TransactionsLastMonth      int64
AvgTxnAmount               int64
ComplaintsLast6M           int64
ComplaintType             object
Churned                   object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10120 entries, 0 to 10119
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             10120 non-null  int64
 1   Age                    10120 non-null  int64
 2   Job                    10120 non-null  object
 3   Marital                10120 non-null  object
 4   Education              9717 non-null   object
 5   City                   10120 non-null  object
 6   Channel                10120 non-null  object
 7   Segment                10120 non-null  object
 8   AccountOpenDate        10120 non-null  object
 9   MonthlyIncome          9817 non-null   object
 10  Balance                9816 non-null   object
 11  CreditScore            9915 non-null   float64
 12  HasHousingLoan         10120 non-null  object
 13  HasPersonalLoan        10120 non-null  object
 14  HasCreditCard          10120 non-null  object
 15  TransactionsLastMonth  10120 non-null  int64
 16  AvgTxnAmount           10120 non-null  int64
 17  ComplaintsLast6M       10120 non-null  int64
 18  ComplaintType          8254 non-null   object
 19  Churned                10120 non-null  object
dtypes: float64(1), int64(5), object(14)
memory usage: 1.5+ MB

## 3) Quick samples

In [ ]:
df.head(10)

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
0,200001,22,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",498.0,Yes,No,Yes,2,28449,3,Charges,No
1,200002,58,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,727.0,Yes,Yes,Yes,18,33378,4,Card,No
2,200003,52,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",310.0,Yes,Yes,Yes,20,19283,6,Charges,No
3,200004,40,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,399.0,No,Yes,No,60,16949,1,NaN,No
4,200005,40,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,369.0,No,No,Yes,36,25336,1,Digital Banking,No
5,200006,62,entrepreneur,single,secondary,Hyderabad,mobile_app,Affluent,12/07/2024,195668.0,528745.0,315.0,No,No,Yes,28,1511,0,Digital Banking,No
6,200007,22,technician,married,tertiary,Karachi,online,Mass,07/04/2025,"96,117",351934.0,306.0,No,No,Yes,57,23909,6,Loan,No
7,200008,54,management,divorced,secondary,Karachi,call_center,Affluent,09/05/2023,"238,746","-116,292",438.0,No,No,Yes,36,37967,0,Service,No
8,200009,28,self-employed,single,tertiary,Lahore,online,Affluent,11/08/2023,"52,936",-112927.0,816.0,Yes,Yes,Yes,44,3196,1,Card,No
9,200010,22,student,single,primary,Karachi,atm,Mass,25/04/2024,204559.0,446257.0,625.0,No,No,Yes,32,24295,1,Service,Yes

In [ ]:
df.tail()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
10115,200116,47,blue-collar,married,secondary,Quetta,mobile_app,SME,15/11/2023,120832.0,-42610.0,393.0,No,No,No,58,17130,2,Digital Banking,No
10116,200117,19,self-employed,divorced,secondary,Lahore,atm,Mass,01/11/2023,140706.0,507124.0,516.0,Yes,No,No,19,47636,2,Digital Banking,No
10117,200118,25,technician,married,primary,Lahore,atm,Affluent,24/02/2025,196257.0,"-269,166",397.0,Yes,No,No,59,8292,3,Card,Yes
10118,200119,30,blue-collar,married,secondary,Lahore,mobile_app,Mass,19/11/2024,201358.0,"144,359",375.0,No,Yes,No,35,22975,4,Loan,Yes
10119,200120,23,student,single,primary,Lahore,branch,Mass,24/10/2024,233839.0,"199,650",533.0,Yes,No,Yes,53,18882,6,Service,No

In [ ]:
df.sample(5, random_state=42)

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
7319,207320,20,retired,divorced,secondary,Islamabad,call_center,SME,22/03/2023,"151,164",270750.0,734.0,Yes,No,Yes,43,32454,0,Loan,No
2919,202920,37,entrepreneur,married,primary,Islamabad,online,Mass,19/01/2024,"140,134","488,482",804.0,Yes,No,No,60,49334,6,Card,Yes
5753,205754,32,technician,married,secondary,Hyderabad,branch,Mass,17/09/2023,32976.0,431828.0,404.0,Yes,No,Yes,33,47626,5,NaN,No
5982,205983,66,admin,married,tertiary,Lahore,online,Affluent,15/01/2023,143309.0,33153.0,829.0,No,No,Yes,35,40597,5,NaN,No
623,200624,39,services,married,tertiary,Quetta,atm,Mass,10/01/2024,103639.0,"595,828",497.0,No,No,Yes,27,20894,5,Loan,No

## 4) Missing values + duplicates

In [ ]:
df.isnull()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10115,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10116,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10117,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10118,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10119,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

CustomerID                  0
Age                         0
Job                         0
Marital                     0
Education                 403
City                        0
Channel                     0
Segment                     0
AccountOpenDate             0
MonthlyIncome             303
Balance                   304
CreditScore               205
HasHousingLoan              0
HasPersonalLoan             0
HasCreditCard               0
TransactionsLastMonth       0
AvgTxnAmount                0
ComplaintsLast6M            0
ComplaintType            1866
Churned                     0
dtype: int64

In [ ]:
df.isnull().sum().sort_values(ascending=False)

ComplaintType            1866
Education                 403
Balance                   304
MonthlyIncome             303
CreditScore               205
Job                         0
Age                         0
CustomerID                  0
Marital                     0
Segment                     0
City                        0
Channel                     0
AccountOpenDate             0
HasHousingLoan              0
HasCreditCard               0
HasPersonalLoan             0
TransactionsLastMonth       0
AvgTxnAmount                0
ComplaintsLast6M            0
Churned                     0
dtype: int64

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10115     True
10116     True
10117     True
10118     True
10119     True
Length: 10120, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(120)

In [ ]:
df = df.drop_duplicates()
df.shape

(10000, 20)

## 5) Clean text columns using `.str.strip()`
Some categories have extra spaces; strip them.

In [ ]:
obj_cols = df.select_dtypes(include="object").columns #string
obj_cols

Index(['Job', 'Marital', 'Education', 'City', 'Channel', 'Segment',
       'AccountOpenDate', 'MonthlyIncome', 'Balance', 'HasHousingLoan',
       'HasPersonalLoan', 'HasCreditCard', 'ComplaintType', 'Churned'],
      dtype='object')

In [ ]:
# Select text columns
obj_cols = df.select_dtypes(include="object").columns

# Remove extra spaces from each text column
for column in obj_cols:
    df[column] = df[column].astype(str)
    df[column] = df[column].str.strip()

# Display the first five rows
df[obj_cols].head()

,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,HasHousingLoan,HasPersonalLoan,HasCreditCard,ComplaintType,Churned
0,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",Yes,No,Yes,Charges,No
1,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,Yes,Yes,Yes,Card,No
2,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",Yes,Yes,Yes,Charges,No
3,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,No,Yes,No,nan,No
4,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,No,No,Yes,Digital Banking,No

In [ ]:
df[obj_cols] = df[obj_cols].apply(lambda s: s.astype("string").str.strip())
df[obj_cols].head()

,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,HasHousingLoan,HasPersonalLoan,HasCreditCard,ComplaintType,Churned
0,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",Yes,No,Yes,Charges,No
1,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,Yes,Yes,Yes,Card,No
2,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",Yes,Yes,Yes,Charges,No
3,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,No,Yes,No,nan,No
4,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,No,No,Yes,Digital Banking,No

## 6) Data type conversion (very important)
### A) Convert strings with commas → numeric using `to_numeric`
Some values look like `'110,000'`.

### B) Convert date string → datetime using `to_datetime`

In [ ]:
df["MonthlyIncome"]

0       193802.0
1         43,340
2        129,068
3       175001.0
4        141,569
          ...
9995      29,080
9996     86729.0
9997    196737.0
9998    217164.0
9999      54,821
Name: MonthlyIncome, Length: 10000, dtype: string

In [ ]:
# Remove commas then convert to numeric
df["MonthlyIncome"] = pd.to_numeric(df["MonthlyIncome"].astype("string").str.replace(",", ""), errors="coerce")
df["Balance"] = pd.to_numeric(df["Balance"].astype("string").str.replace(",", ""), errors="coerce")
#abc,missing - nan
# Convert date string to datetime
df["AccountOpenDate"] = pd.to_datetime(df["AccountOpenDate"], errors="coerce")

df.dtypes

/tmp/ipykernel_2102/3297343620.py:6: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["AccountOpenDate"] = pd.to_datetime(df["AccountOpenDate"], errors="coerce")

CustomerID                        int64
Age                               int64
Job                      string[python]
Marital                  string[python]
Education                string[python]
City                     string[python]
Channel                  string[python]
Segment                  string[python]
AccountOpenDate          datetime64[ns]
MonthlyIncome                   Float64
Balance                         Float64
CreditScore                     float64
HasHousingLoan           string[python]
HasPersonalLoan          string[python]
HasCreditCard            string[python]
TransactionsLastMonth             int64
AvgTxnAmount                      int64
ComplaintsLast6M                  int64
ComplaintType            string[python]
Churned                  string[python]
dtype: object

## 7) Fill missing values (basic)
- Numeric → median
- Categorical → mode

In [ ]:
num_cols = df.select_dtypes(include=["int64","float64"]).columns
cat_cols = df.select_dtypes(include="object").columns

df[num_cols] = df[num_cols].fillna(df[num_cols].median(numeric_only=True))
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

df.isnull().sum().sort_values(ascending=False).head(10)

IndexError: single positional indexer is out-of-bounds

## 8) Basic EDA summaries

In [ ]:
df.describe()

,CustomerID,Age,AccountOpenDate,MonthlyIncome,Balance,CreditScore,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M
count,10000.00000,10000.000000,10000,10000.0,10000.0,10000.000000,10000.000000,10000.000000,10000.000000
mean,205000.50000,43.306300,2024-03-31 20:17:13.920000,137728.9684,128652.6471,600.457000,30.153600,25198.562200,2.992400
min,200001.00000,18.000000,2023-01-01 00:00:00,-249987.0,-349915.0,300.000000,0.000000,501.000000,0.000000
25%,202500.75000,30.000000,2023-08-16 00:00:00,83659.75,-97661.0,454.000000,15.000000,12823.250000,1.000000
50%,205000.50000,43.000000,2024-04-02 00:00:00,138008.0,130862.0,598.000000,30.000000,25206.000000,3.000000
75%,207500.25000,56.000000,2024-11-12 00:00:00,193302.25,356805.75,745.000000,45.000000,37675.250000,5.000000
max,210000.00000,69.000000,2025-06-29 00:00:00,249978.0,599935.0,900.000000,60.000000,49991.000000,6.000000
std,2886.89568,14.935561,NaN,65287.223485,269055.536709,171.198115,17.504549,14313.548955,2.006725

In [ ]:
df.nunique().sort_values(ascending=False).head(10)

CustomerID               10000
Balance                   9648
MonthlyIncome             9495
AvgTxnAmount              9080
AccountOpenDate            911
CreditScore                601
TransactionsLastMonth       61
Age                         52
Job                          9
ComplaintType                7
dtype: int64

In [ ]:
df["Job"].value_counts().head(10)

Job
retired          1163
student          1151
technician       1147
entrepreneur     1122
services         1097
self-employed    1096
management       1096
blue-collar      1066
admin            1062
Name: count, dtype: Int64

In [ ]:
df["City"].value_counts(normalize=True).head(10) * 100

City
Quetta       20.28
Karachi      20.24
Islamabad    20.08
Lahore       20.07
Hyderabad    19.33
Name: proportion, dtype: Float64

## 9) Sorting + filtering

In [ ]:
df.sort_values("Balance", ascending=False).head(5)[["CustomerID","City","Balance","MonthlyIncome","CreditScore"]]

      CustomerID       City   Balance  MonthlyIncome  CreditScore
4972      204973     Quetta  599935.0       138008.0        481.0
7540      207541     Lahore  599696.0       138008.0        538.0
8180      208181  Hyderabad  599617.0       105167.0        642.0
4118      204119  Hyderabad  599405.0       111235.0        872.0
625       200626  Islamabad  599261.0       107185.0        829.0

In [ ]:
# Filter: high credit score and not churned
df[(df["CreditScore"] >= 750) & (df["Churned"] == "No")].head()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
8,200009,28,self-employed,single,tertiary,Lahore,online,Affluent,2023-08-11,52936.0,-112927.0,816.0,Yes,Yes,Yes,44,3196,1,Card,No
10,200011,45,technician,married,secondary,Islamabad,atm,Mass,2024-05-01,188356.0,314092.0,755.0,Yes,No,Yes,24,10337,4,nan,No
12,200013,56,technician,single,secondary,Hyderabad,call_center,SME,2023-05-15,80258.0,-82401.0,840.0,No,No,Yes,22,11547,0,Digital Banking,No
15,200016,58,technician,single,secondary,Quetta,branch,Affluent,2023-06-17,203183.0,424395.0,770.0,Yes,Yes,Yes,51,5567,1,Service,No
25,200026,51,management,single,secondary,Hyderabad,branch,Mass,2023-04-07,88627.0,19773.0,830.0,No,Yes,Yes,8,5676,4,Digital Banking,No

## 10) `query()` (easy syntax for students)

In [ ]:
df.query("CreditScore >= 700 and TransactionsLastMonth >= 40").head()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
8,200009,28,self-employed,single,tertiary,Lahore,online,Affluent,2023-08-11,52936.0,-112927.0,816.0,Yes,Yes,Yes,44,3196,1,Card,No
13,200014,57,entrepreneur,single,secondary,Karachi,online,Mass,2024-03-16,237293.0,527387.0,864.0,No,No,Yes,57,22515,3,Loan,Yes
15,200016,58,technician,single,secondary,Quetta,branch,Affluent,2023-06-17,203183.0,424395.0,770.0,Yes,Yes,Yes,51,5567,1,Service,No
33,200034,46,blue-collar,single,secondary,Lahore,atm,SME,2025-02-27,41402.0,445195.0,779.0,No,No,Yes,45,26100,2,Charges,No
35,200036,21,blue-collar,divorced,secondary,Karachi,call_center,Mass,2024-01-13,30420.0,259728.0,825.0,No,Yes,Yes,41,20987,2,Digital Banking,Yes

## 11) `loc` and `iloc`

In [ ]:
df.loc[df["HasCreditCard"] == "Yes", ["CustomerID","Age","City","Balance","HasCreditCard"]].head()

   CustomerID  Age       City   Balance HasCreditCard
0      200001   22    Karachi  216975.0           Yes
1      200002   58     Lahore  103887.0           Yes
2      200003   52     Quetta  461004.0           Yes
4      200005   40    Karachi  554801.0           Yes
5      200006   62  Hyderabad  528745.0           Yes

In [ ]:
df.iloc[:5, :8]

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment
0,200001,22,retired,married,tertiary,Karachi,call_center,Mass
1,200002,58,management,married,unknown,Lahore,branch,Mass
2,200003,52,blue-collar,single,primary,Quetta,mobile_app,Mass
3,200004,40,technician,single,secondary,Islamabad,branch,Mass
4,200005,40,services,single,secondary,Karachi,atm,SME

## 12) `where()` example
Mark unrealistically negative income as missing, then fill again.

In [ ]:
df["MonthlyIncome"] = df["MonthlyIncome"].where(df["MonthlyIncome"] > 0, np.nan)
df["MonthlyIncome"] = df["MonthlyIncome"].fillna(df["MonthlyIncome"].median())
df[["MonthlyIncome"]].head()

   MonthlyIncome
0       193802.0
1        43340.0
2       129068.0
3       175001.0
4       141569.0

## 13) Groupby + aggregation

In [ ]:
(df.groupby("Segment")
   .agg(avg_balance=("Balance","mean"),
        avg_income=("MonthlyIncome","mean"),
        customers=("CustomerID","count"),
        churn_rate=("Churned", lambda s: (s=="Yes").mean()*100))
   .sort_values("avg_balance", ascending=False)
).head(10)

            avg_balance     avg_income  customers  churn_rate
Segment
SME       133933.385751  138977.295674       1965   18.524173
Affluent  129216.985948  139137.062451       2562   18.618267
Mass      126492.499543  137585.013521       5473   18.509044

## 14) Pivot table

In [ ]:
pd.pivot_table(df, values="Balance", index="City", columns="Segment", aggfunc="mean").head()

Segment         Affluent           Mass            SME
City
Hyderabad  131981.336735  126181.170528  126936.098901
Islamabad  119384.251462  125990.141947  154175.138889
Karachi      135408.8577  134795.381039  138452.231884
Lahore      106102.13371  125701.695291  109101.452926
Quetta     154046.533981  119888.190135  140012.344221

## 15) Crosstab (category vs category)

In [ ]:
pd.crosstab(df["HasHousingLoan"], df["Churned"], normalize="index") * 100

Churned                No        Yes
HasHousingLoan
No              82.269631  17.730369
Yes             80.438716  19.561284

## 16) Correlation (numeric only)
Useful before ML.

In [ ]:
df.corr(numeric_only=True)

,CustomerID,Age,MonthlyIncome,Balance,CreditScore,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M
CustomerID,1.000000,-0.006929,0.008547,-0.005720,-0.008604,-0.013705,0.007724,-0.000552
Age,-0.006929,1.000000,-0.003887,0.007635,0.002212,0.002600,-0.009767,-0.012746
MonthlyIncome,0.008547,-0.003887,1.000000,0.001901,0.000956,0.001559,-0.002100,-0.004663
Balance,-0.005720,0.007635,0.001901,1.000000,-0.000018,-0.001137,0.000449,-0.005119
CreditScore,-0.008604,0.002212,0.000956,-0.000018,1.000000,-0.009257,-0.003235,0.000118
TransactionsLastMonth,-0.013705,0.002600,0.001559,-0.001137,-0.009257,1.000000,-0.016755,-0.011529
AvgTxnAmount,0.007724,-0.009767,-0.002100,0.000449,-0.003235,-0.016755,1.000000,-0.007746
ComplaintsLast6M,-0.000552,-0.012746,-0.004663,-0.005119,0.000118,-0.011529,-0.007746,1.000000

## 17) Binning with `pd.cut()`
Create age groups.

In [ ]:
bins = [0, 25, 35, 45, 60, 100]
labels = ["<=25","26-35","36-45","46-60","60+"]
df["AgeGroup"] = pd.cut(df["Age"], bins=bins, labels=labels)
df["AgeGroup"].value_counts()

AgeGroup
46-60    2833
26-35    2001
36-45    1940
60+      1682
<=25     1544
Name: count, dtype: int64

## 18) Replace values (basic cleaning)

In [ ]:
# Example: replace 'unknown' education with 'secondary'
df["Education"] = df["Education"].replace("unknown", "secondary")
df["Education"].value_counts().head()

Education
secondary    4738
tertiary     3144
primary      1715
nan           403
Name: count, dtype: Int64

# Visualizations (Matplotlib)
We keep visuals simple for classroom demo.

## 19) Histogram: Balance distribution

In [ ]:
plt.figure()
plt.hist(df["Balance"], bins=30)
plt.xlabel("Balance")
plt.ylabel("Frequency")
plt.title("Balance Distribution")
plt.show()

## 20) Bar chart: Job counts

In [ ]:
plt.figure()
job_counts = df["Job"].value_counts().head(8)
plt.bar(job_counts.index.astype(str), job_counts.values)
plt.xticks(rotation=45)
plt.xlabel("Job")
plt.ylabel("Count")
plt.title("Top Job Categories")
plt.show()

## 21) Boxplot: Balance by Segment

In [ ]:
plt.figure()
# Prepare data for boxplot
segments = df["Segment"].unique()
data = [df.loc[df["Segment"]==seg, "Balance"] for seg in segments]
plt.boxplot(data, labels=[str(s) for s in segments], showfliers=False)
plt.xticks(rotation=45)
plt.xlabel("Segment")
plt.ylabel("Balance")
plt.title("Balance by Segment (Boxplot)")
plt.show()

## 22) Scatter: MonthlyIncome vs Balance

In [ ]:
plt.figure()
plt.scatter(df["MonthlyIncome"], df["Balance"], s=8)
plt.xlabel("Monthly Income")
plt.ylabel("Balance")
plt.title("Income vs Balance (Scatter)")
plt.show()

## 23) Line plot: Customers opened accounts over time

In [ ]:
opened_per_month = df.set_index("AccountOpenDate").resample("M")["CustomerID"].count()
plt.figure()
plt.plot(opened_per_month.index, opened_per_month.values)
plt.xlabel("Month")
plt.ylabel("New Accounts")
plt.title("Accounts Opened Per Month")
plt.show()

## 24) Save cleaned dataset

In [ ]:
df.to_csv("cleaned_banking_eda_dataset.csv", index=False)
print("Saved: cleaned_banking_eda_dataset.csv")