In [ ]:
#!pip install pandas

In [ ]:
import pandas as pd #elias
import numpy as np

df = pd.read_csv("banking.csv")

In [ ]:
df

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
0,200001,22,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",498.0,Yes,No,Yes,2,28449,3,Charges,No
1,200002,58,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,727.0,Yes,Yes,Yes,18,33378,4,Card,No
2,200003,52,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",310.0,Yes,Yes,Yes,20,19283,6,Charges,No
3,200004,40,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,399.0,No,Yes,No,60,16949,1,NaN,No
4,200005,40,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,369.0,No,No,Yes,36,25336,1,Digital Banking,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10115,200116,47,blue-collar,married,secondary,Quetta,mobile_app,SME,15/11/2023,120832.0,-42610.0,393.0,No,No,No,58,17130,2,Digital Banking,No
10116,200117,19,self-employed,divorced,secondary,Lahore,atm,Mass,01/11/2023,140706.0,507124.0,516.0,Yes,No,No,19,47636,2,Digital Banking,No
10117,200118,25,technician,married,primary,Lahore,atm,Affluent,24/02/2025,196257.0,"-269,166",397.0,Yes,No,No,59,8292,3,Card,Yes
10118,200119,30,blue-collar,married,secondary,Lahore,mobile_app,Mass,19/11/2024,201358.0,"144,359",375.0,No,Yes,No,35,22975,4,Loan,Yes
10119,200120,23,student,single,primary,Lahore,branch,Mass,24/10/2024,233839.0,"199,650",533.0,Yes,No,Yes,53,18882,6,Service,No

In [ ]:
df.head()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
0,200001,22,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",498.0,Yes,No,Yes,2,28449,3,Charges,No
1,200002,58,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,727.0,Yes,Yes,Yes,18,33378,4,Card,No
2,200003,52,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",310.0,Yes,Yes,Yes,20,19283,6,Charges,No
3,200004,40,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,399.0,No,Yes,No,60,16949,1,NaN,No
4,200005,40,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,369.0,No,No,Yes,36,25336,1,Digital Banking,No

In [ ]:
df.tail()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
10115,200116,47,blue-collar,married,secondary,Quetta,mobile_app,SME,15/11/2023,120832.0,-42610.0,393.0,No,No,No,58,17130,2,Digital Banking,No
10116,200117,19,self-employed,divorced,secondary,Lahore,atm,Mass,01/11/2023,140706.0,507124.0,516.0,Yes,No,No,19,47636,2,Digital Banking,No
10117,200118,25,technician,married,primary,Lahore,atm,Affluent,24/02/2025,196257.0,"-269,166",397.0,Yes,No,No,59,8292,3,Card,Yes
10118,200119,30,blue-collar,married,secondary,Lahore,mobile_app,Mass,19/11/2024,201358.0,"144,359",375.0,No,Yes,No,35,22975,4,Loan,Yes
10119,200120,23,student,single,primary,Lahore,branch,Mass,24/10/2024,233839.0,"199,650",533.0,Yes,No,Yes,53,18882,6,Service,No

In [ ]:
df.shape #number of rows, no of columns

(10120, 20)

In [ ]:
df.columns

Index(['CustomerID', 'Age', 'Job', 'Marital', 'Education', 'City', 'Channel',
       'Segment', 'AccountOpenDate', 'MonthlyIncome', 'Balance', 'CreditScore',
       'HasHousingLoan', 'HasPersonalLoan', 'HasCreditCard',
       'TransactionsLastMonth', 'AvgTxnAmount', 'ComplaintsLast6M',
       'ComplaintType', 'Churned'],
      dtype='object')

In [ ]:
df.dtypes

CustomerID                 int64
Age                        int64
Job                       object
Marital                   object
Education                 object
City                      object
Channel                   object
Segment                   object
AccountOpenDate           object
MonthlyIncome             object
Balance                   object
CreditScore              float64
HasHousingLoan            object
HasPersonalLoan           object
HasCreditCard             object
TransactionsLastMonth      int64
AvgTxnAmount               int64
ComplaintsLast6M           int64
ComplaintType             object
Churned                   object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10120 entries, 0 to 10119
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             10120 non-null  int64
 1   Age                    10120 non-null  int64
 2   Job                    10120 non-null  object
 3   Marital                10120 non-null  object
 4   Education              9717 non-null   object
 5   City                   10120 non-null  object
 6   Channel                10120 non-null  object
 7   Segment                10120 non-null  object
 8   AccountOpenDate        10120 non-null  object
 9   MonthlyIncome          9817 non-null   object
 10  Balance                9816 non-null   object
 11  CreditScore            9915 non-null   float64
 12  HasHousingLoan         10120 non-null  object
 13  HasPersonalLoan        10120 non-null  object
 14  HasCreditCard          10120 non-null  object
 15  TransactionsLastMonth  10120 non-null  int64
 16  AvgTxnAmount           10120 non-null  int64
 17  ComplaintsLast6M       10120 non-null  int64
 18  ComplaintType          8254 non-null   object
 19  Churned                10120 non-null  object
dtypes: float64(1), int64(5), object(14)
memory usage: 1.5+ MB

In [ ]:
df.sample(10)

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
3685,203686,26,entrepreneur,single,secondary,Quetta,branch,Mass,17/05/2024,87523.0,"315,413",886.0,No,No,Yes,23,23116,6,NaN,No
748,200749,34,student,married,tertiary,Karachi,online,Mass,06/12/2023,171558.0,17341.0,443.0,No,No,Yes,47,11535,1,Charges,No
6127,206128,63,entrepreneur,single,secondary,Islamabad,atm,SME,10/05/2023,166510.0,-82331.0,319.0,Yes,No,No,59,22105,2,Charges,No
8583,208584,21,admin,divorced,secondary,Karachi,branch,Mass,01/01/2025,52265.0,"325,302",676.0,Yes,No,Yes,37,42725,0,Loan,No
2340,202341,40,technician,married,primary,Karachi,mobile_app,Mass,17/06/2024,"76,768","266,244",831.0,No,No,No,52,30571,5,NaN,No
9796,209797,50,retired,married,tertiary,Lahore,online,Affluent,03/12/2023,124114.0,"305,867",444.0,Yes,Yes,Yes,5,26463,4,NaN,No
3957,203958,56,admin,married,secondary,Islamabad,mobile_app,Affluent,21/12/2023,198102.0,67266.0,365.0,No,No,Yes,55,23610,0,Loan,No
7968,207969,18,blue-collar,single,secondary,Quetta,mobile_app,Mass,25/04/2024,164703.0,"115,534",850.0,No,Yes,Yes,36,13091,3,Charges,Yes
8083,208084,57,management,married,NaN,Hyderabad,branch,Mass,13/11/2023,"26,549",89645.0,696.0,No,No,Yes,13,31825,6,Card,No
7432,207433,37,retired,single,secondary,Hyderabad,branch,Mass,02/06/2025,"122,221",543075.0,896.0,Yes,No,Yes,19,26227,1,Card,No

In [ ]:
#Missing_ value + Duplicates
df.isnull()

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10115,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10116,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10117,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10118,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10119,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

CustomerID                  0
Age                         0
Job                         0
Marital                     0
Education                 403
City                        0
Channel                     0
Segment                     0
AccountOpenDate             0
MonthlyIncome             303
Balance                   304
CreditScore               205
HasHousingLoan              0
HasPersonalLoan             0
HasCreditCard               0
TransactionsLastMonth       0
AvgTxnAmount                0
ComplaintsLast6M            0
ComplaintType            1866
Churned                     0
dtype: int64

In [ ]:
df.isnull().sum().sort_values(ascending=False)

ComplaintType            1866
Education                 403
Balance                   304
MonthlyIncome             303
CreditScore               205
Job                         0
Age                         0
CustomerID                  0
Marital                     0
Segment                     0
City                        0
Channel                     0
AccountOpenDate             0
HasHousingLoan              0
HasCreditCard               0
HasPersonalLoan             0
TransactionsLastMonth       0
AvgTxnAmount                0
ComplaintsLast6M            0
Churned                     0
dtype: int64

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10115     True
10116     True
10117     True
10118     True
10119     True
Length: 10120, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(120)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(10000, 20)

In [ ]:
#Clean text columns using .str.strip()
df['job'] = df['job'].str.strip()
df['marital'] = df['marital'].str.strip()
df['education'] = df['education'].str.strip()
df['default'] = df['default'].str.strip()
df['housing'] = df['housing'].str.strip()
df['loan'] = df['loan'].str.strip()
df['contact'] = df['contact'].str.strip()
df['month'] = df['month'].str.strip()
df['poutcome'] = df['poutcome'].str.strip()

KeyError: 'job'

In [ ]:
obj_cols = df.select_dtypes(include='object').columns
obj_cols

Index(['Job', 'Marital', 'Education', 'City', 'Channel', 'Segment',
       'AccountOpenDate', 'MonthlyIncome', 'Balance', 'HasHousingLoan',
       'HasPersonalLoan', 'HasCreditCard', 'ComplaintType', 'Churned'],
      dtype='object')

In [ ]:
df["Job"]

0           retired
1        management
2       blue-collar
3        technician
4          services
           ...
9995     management
9996     management
9997        retired
9998        retired
9999    blue-collar
Name: Job, Length: 10000, dtype: object

In [ ]:
for column in obj_cols:
  df[column]= df[column].astype(str)
  df[column]= df[column].str.strip()
df[obj_cols].head()

/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()
/tmp/ipykernel_1648/2797424715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].astype(str)
/tmp/ipykernel_1648/2797424715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column]= df[column].str.strip()

,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,HasHousingLoan,HasPersonalLoan,HasCreditCard,ComplaintType,Churned
0,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",Yes,No,Yes,Charges,No
1,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,Yes,Yes,Yes,Card,No
2,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",Yes,Yes,Yes,Charges,No
3,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,No,Yes,No,nan,No
4,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,No,No,Yes,Digital Banking,No

In [ ]:
df[obj_cols] = df[obj_cols].apply(lambda x: x.astype(str).str.strip())
df[obj_cols].head()

/tmp/ipykernel_1648/1584825695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[obj_cols] = df[obj_cols].apply(lambda x: x.astype(str).str.strip())

,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,HasHousingLoan,HasPersonalLoan,HasCreditCard,ComplaintType,Churned
0,retired,married,tertiary,Karachi,call_center,Mass,31/10/2024,193802.0,"216,975",Yes,No,Yes,Charges,No
1,management,married,unknown,Lahore,branch,Mass,14/03/2025,"43,340",103887.0,Yes,Yes,Yes,Card,No
2,blue-collar,single,primary,Quetta,mobile_app,Mass,04/06/2024,"129,068","461,004",Yes,Yes,Yes,Charges,No
3,technician,single,secondary,Islamabad,branch,Mass,13/01/2024,175001.0,441345.0,No,Yes,No,nan,No
4,services,single,secondary,Karachi,atm,SME,05/01/2023,"141,569",554801.0,No,No,Yes,Digital Banking,No

In [ ]:
#data type conversion

In [ ]:
df["MonthlyIncome"]

0       193802.0
1         43,340
2        129,068
3       175001.0
4        141,569
          ...
9995      29,080
9996     86729.0
9997    196737.0
9998    217164.0
9999      54,821
Name: MonthlyIncome, Length: 10000, dtype: object

In [ ]:
df["MonthlyIncome"] = df["MonthlyIncome"].astype(str)

/tmp/ipykernel_1648/752011586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["MonthlyIncome"] = df["MonthlyIncome"].astype(str)

In [ ]:
df["MonthlyIncome"] = df["MonthlyIncome"].str.replace(",","")

/tmp/ipykernel_1648/741791495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["MonthlyIncome"] = df["MonthlyIncome"].str.replace(",","")

In [ ]:
df["MonthlyIncome"] = pd.to_numeric(df["MonthlyIncome"], errors="coerce")

/tmp/ipykernel_1648/248792895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["MonthlyIncome"] = pd.to_numeric(df["MonthlyIncome"], errors="coerce")

In [ ]:
df["MonthlyIncome"] = pd.to_numeric(df["MonthlyIncome"].astype(str).str.replace(",",""), errors="coerce")#"raise","ignore", missing - NaN

/tmp/ipykernel_1648/3663864333.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["MonthlyIncome"] = pd.to_numeric(df["MonthlyIncome"].astype(str).str.replace(",",""), errors="coerce")#"raise","ignore", missing - NaN

In [ ]:
df["MonthlyIncome"].dtypes

dtype('float64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             10000 non-null  int64
 1   Age                    10000 non-null  int64
 2   Job                    10000 non-null  object
 3   Marital                10000 non-null  object
 4   Education              10000 non-null  object
 5   City                   10000 non-null  object
 6   Channel                10000 non-null  object
 7   Segment                10000 non-null  object
 8   AccountOpenDate        10000 non-null  object
 9   MonthlyIncome          9697 non-null   float64
 10  Balance                10000 non-null  object
 11  CreditScore            9795 non-null   float64
 12  HasHousingLoan         10000 non-null  object
 13  HasPersonalLoan        10000 non-null  object
 14  HasCreditCard          10000 non-null  object
 15  TransactionsLastMonth  10000 non-null  int64
 16  AvgTxnAmount           10000 non-null  int64
 17  ComplaintsLast6M       10000 non-null  int64
 18  ComplaintType          10000 non-null  object
 19  Churned                10000 non-null  object
dtypes: float64(2), int64(5), object(13)
memory usage: 1.6+ MB

In [ ]:
df["Balance"] = pd.to_numeric(df["Balance"].astype(str).str.replace(",",""), errors="coerce")#"raise","ignore", missing - NaN

/tmp/ipykernel_1648/3325973658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Balance"] = pd.to_numeric(df["Balance"].astype(str).str.replace(",",""), errors="coerce")#"raise","ignore", missing - NaN

In [ ]:
df["Balance"].dtypes

dtype('float64')

In [ ]:
df["AccountOpenDate"] = pd.to_datetime(df["AccountOpenDate"], errors="coerce")

/tmp/ipykernel_1648/4262909069.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["AccountOpenDate"] = pd.to_datetime(df["AccountOpenDate"], errors="coerce")
/tmp/ipykernel_1648/4262909069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["AccountOpenDate"] = pd.to_datetime(df["AccountOpenDate"], errors="coerce")

In [ ]:
df["AccountOpenDate"].dtypes

dtype('<M8[ns]')

In [ ]:
df.dtypes

CustomerID                        int64
Age                               int64
Job                              object
Marital                          object
Education                        object
City                             object
Channel                          object
Segment                          object
AccountOpenDate          datetime64[ns]
MonthlyIncome                   float64
Balance                         float64
CreditScore                     float64
HasHousingLoan                   object
HasPersonalLoan                  object
HasCreditCard                    object
TransactionsLastMonth             int64
AvgTxnAmount                      int64
ComplaintsLast6M                  int64
ComplaintType                    object
Churned                          object
dtype: object

In [ ]:
#fill the missing value outliers
#numeric - median/mean
#categorical - mode
num_cols = df.select_dtypes(include=["int64","float64"]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

In [ ]:
num_cols

Index(['CustomerID', 'Age', 'MonthlyIncome', 'Balance', 'CreditScore',
       'TransactionsLastMonth', 'AvgTxnAmount', 'ComplaintsLast6M'],
      dtype='object')

In [ ]:
cat_cols

Index(['Job', 'Marital', 'Education', 'City', 'Channel', 'Segment',
       'HasHousingLoan', 'HasPersonalLoan', 'HasCreditCard', 'ComplaintType',
       'Churned'],
      dtype='object')

In [ ]:
#df["MonthlyIncome"] = df["MonthlyIncome"].fillna(df["MonthlyIncome"].mean())

In [ ]:
df[num_cols] = df[num_cols].fillna(df[num_cols].median(numeric_only=True))

/tmp/ipykernel_1648/252692067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[num_cols] = df[num_cols].fillna(df[num_cols].median(numeric_only=True))

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             10000 non-null  int64
 1   Age                    10000 non-null  int64
 2   Job                    10000 non-null  object
 3   Marital                10000 non-null  object
 4   Education              10000 non-null  object
 5   City                   10000 non-null  object
 6   Channel                10000 non-null  object
 7   Segment                10000 non-null  object
 8   AccountOpenDate        10000 non-null  datetime64[ns]
 9   MonthlyIncome          10000 non-null  float64
 10  Balance                10000 non-null  float64
 11  CreditScore            10000 non-null  float64
 12  HasHousingLoan         10000 non-null  object
 13  HasPersonalLoan        10000 non-null  object
 14  HasCreditCard          10000 non-null  object
 15  TransactionsLastMonth  10000 non-null  int64
 16  AvgTxnAmount           10000 non-null  int64
 17  ComplaintsLast6M       10000 non-null  int64
 18  ComplaintType          10000 non-null  object
 19  Churned                10000 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(5), object(11)
memory usage: 1.6+ MB

In [ ]:
df.describe()

,CustomerID,Age,AccountOpenDate,MonthlyIncome,Balance,CreditScore,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M
count,10000.00000,10000.000000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,205000.50000,43.306300,2024-03-31 20:17:13.920000,137728.968400,128652.647100,600.457000,30.153600,25198.562200,2.992400
min,200001.00000,18.000000,2023-01-01 00:00:00,-249987.000000,-349915.000000,300.000000,0.000000,501.000000,0.000000
25%,202500.75000,30.000000,2023-08-16 00:00:00,83659.750000,-97661.000000,454.000000,15.000000,12823.250000,1.000000
50%,205000.50000,43.000000,2024-04-02 00:00:00,138008.000000,130862.000000,598.000000,30.000000,25206.000000,3.000000
75%,207500.25000,56.000000,2024-11-12 00:00:00,193302.250000,356805.750000,745.000000,45.000000,37675.250000,5.000000
max,210000.00000,69.000000,2025-06-29 00:00:00,249978.000000,599935.000000,900.000000,60.000000,49991.000000,6.000000
std,2886.89568,14.935561,NaN,65287.223485,269055.536709,171.198115,17.504549,14313.548955,2.006725

In [ ]:
df.nunique().sort_values(ascending=False).head(10)

CustomerID               10000
Balance                   9648
MonthlyIncome             9495
AvgTxnAmount              9080
AccountOpenDate            911
CreditScore                601
TransactionsLastMonth       61
Age                         52
Job                          9
ComplaintType                7
dtype: int64

In [ ]:
df["Marital"].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [ ]:
df["Job"].value_counts(normalize=True) *100

Job
retired          11.63
student          11.51
technician       11.47
entrepreneur     11.22
services         10.97
self-employed    10.96
management       10.96
blue-collar      10.66
admin            10.62
Name: proportion, dtype: float64

In [ ]:
#sorting/Filtering

In [ ]:
df.sort_values("Balance",ascending=False)[["CustomerID","City","Balance","MonthlyIncome","CreditScore"]]

      CustomerID       City   Balance  MonthlyIncome  CreditScore
4972      204973     Quetta  599935.0       138008.0        481.0
7540      207541     Lahore  599696.0       138008.0        538.0
8180      208181  Hyderabad  599617.0       105167.0        642.0
4118      204119  Hyderabad  599405.0       111235.0        872.0
625       200626  Islamabad  599261.0       107185.0        829.0
...          ...        ...       ...            ...          ...
5217      205218  Islamabad -349427.0       151504.0        554.0
4205      204206  Islamabad -349428.0        88682.0        895.0
4584      204585     Quetta -349817.0       215474.0        338.0
2721      202722    Karachi -349849.0        30567.0        741.0
8846      208847     Quetta -349915.0        86911.0        823.0

[10000 rows x 5 columns]

In [ ]:
#Filtering:High Credit Score and not churned
chu = df[(df["CreditScore"]>=700) & (df["Churned"]=="No")]

In [ ]:
chu

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
1,200002,58,management,married,unknown,Lahore,branch,Mass,2025-03-14,43340.0,103887.0,727.0,Yes,Yes,Yes,18,33378,4,Card,No
8,200009,28,self-employed,single,tertiary,Lahore,online,Affluent,2023-08-11,52936.0,-112927.0,816.0,Yes,Yes,Yes,44,3196,1,Card,No
10,200011,45,technician,married,secondary,Islamabad,atm,Mass,2024-05-01,188356.0,314092.0,755.0,Yes,No,Yes,24,10337,4,nan,No
12,200013,56,technician,single,secondary,Hyderabad,call_center,SME,2023-05-15,80258.0,-82401.0,840.0,No,No,Yes,22,11547,0,Digital Banking,No
15,200016,58,technician,single,secondary,Quetta,branch,Affluent,2023-06-17,203183.0,424395.0,770.0,Yes,Yes,Yes,51,5567,1,Service,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,209986,54,retired,married,primary,Karachi,atm,Affluent,2023-02-01,31785.0,431276.0,765.0,Yes,Yes,No,8,3251,2,Charges,No
9986,209987,43,blue-collar,married,secondary,Islamabad,online,Mass,2024-07-08,92154.0,2467.0,805.0,Yes,No,Yes,26,35206,0,nan,No
9988,209989,52,retired,married,unknown,Islamabad,mobile_app,Mass,2025-03-05,203148.0,590235.0,709.0,No,Yes,Yes,4,29746,1,Charges,No
9990,209991,34,self-employed,married,secondary,Islamabad,call_center,Mass,2023-11-09,225890.0,-175953.0,803.0,Yes,No,Yes,4,36417,3,Service,No
9993,209994,26,services,single,secondary,Hyderabad,online,Mass,2024-01-15,100126.0,-261482.0,786.0,Yes,No,Yes,43,33258,2,nan,No

In [ ]:
#query()
df.query("CreditScore>=700 and TransactionsLastMonth >=40")

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment,AccountOpenDate,MonthlyIncome,Balance,CreditScore,HasHousingLoan,HasPersonalLoan,HasCreditCard,TransactionsLastMonth,AvgTxnAmount,ComplaintsLast6M,ComplaintType,Churned
8,200009,28,self-employed,single,tertiary,Lahore,online,Affluent,2023-08-11,52936.0,-112927.0,816.0,Yes,Yes,Yes,44,3196,1,Card,No
13,200014,57,entrepreneur,single,secondary,Karachi,online,Mass,2024-03-16,237293.0,527387.0,864.0,No,No,Yes,57,22515,3,Loan,Yes
15,200016,58,technician,single,secondary,Quetta,branch,Affluent,2023-06-17,203183.0,424395.0,770.0,Yes,Yes,Yes,51,5567,1,Service,No
33,200034,46,blue-collar,single,secondary,Lahore,atm,SME,2025-02-27,41402.0,445195.0,779.0,No,No,Yes,45,26100,2,Charges,No
35,200036,21,blue-collar,divorced,secondary,Karachi,call_center,Mass,2024-01-13,30420.0,259728.0,825.0,No,Yes,Yes,41,20987,2,Digital Banking,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,209977,28,technician,married,secondary,Islamabad,branch,Mass,2024-12-11,247408.0,387445.0,794.0,No,No,No,40,33982,1,Charges,No
9979,209980,23,retired,single,primary,Hyderabad,call_center,Mass,2023-11-21,122079.0,353628.0,823.0,No,No,No,55,11410,1,nan,No
9983,209984,62,retired,married,tertiary,Islamabad,mobile_app,SME,2024-12-17,188756.0,159836.0,778.0,Yes,No,Yes,58,7595,5,Loan,No
9987,209988,36,management,married,secondary,Lahore,online,Mass,2024-09-05,180713.0,-195462.0,705.0,Yes,Yes,No,55,48768,3,Digital Banking,Yes
9993,209994,26,services,single,secondary,Hyderabad,online,Mass,2024-01-15,100126.0,-261482.0,786.0,Yes,No,Yes,43,33258,2,nan,No

In [ ]:
#loc and iloc
df.loc[df["HasCreditCard"]=="Yes",["CustomerID","Age","City","Balance","HasCreditCard"]]

      CustomerID  Age       City   Balance HasCreditCard
0         200001   22    Karachi  216975.0           Yes
1         200002   58     Lahore  103887.0           Yes
2         200003   52     Quetta  461004.0           Yes
4         200005   40    Karachi  554801.0           Yes
5         200006   62  Hyderabad  528745.0           Yes
...          ...  ...        ...       ...           ...
9994      209995   67  Hyderabad -116520.0           Yes
9995      209996   42  Islamabad  564067.0           Yes
9996      209997   69  Hyderabad -284874.0           Yes
9997      209998   36     Lahore  130862.0           Yes
9998      209999   47     Lahore -317645.0           Yes

[6786 rows x 5 columns]

In [ ]:
df.iloc[:5,:8]

,CustomerID,Age,Job,Marital,Education,City,Channel,Segment
0,200001,22,retired,married,tertiary,Karachi,call_center,Mass
1,200002,58,management,married,unknown,Lahore,branch,Mass
2,200003,52,blue-collar,single,primary,Quetta,mobile_app,Mass
3,200004,40,technician,single,secondary,Islamabad,branch,Mass
4,200005,40,services,single,secondary,Karachi,atm,SME

In [ ]:
#where
df["MonthlyIncome"] = df["MonthlyIncome"].where(df["MonthlyIncome"]> 0,np.nan)

/tmp/ipykernel_1648/3006494295.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["MonthlyIncome"] = df["MonthlyIncome"].where(df["MonthlyIncome"]> 0,np.nan)

In [ ]:
pd.pivot_table(df,values="Balance",index="City",columns="Churned",aggfunc="mean")
#

Churned               No            Yes
City
Hyderabad  131426.753973  111918.872222
Islamabad  134338.143911  110803.193717
Karachi    132760.264582  149235.958449
Lahore     116175.323636  122304.638655
Quetta     130820.210526  139527.883249